// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IMdiArrowLeft: typeof import('~icons/mdi/arrow-left')['default']
    IMdiAt: typeof import('~icons/mdi/at')['default']
    IMdiBriefcase: typeof import('~icons/mdi/briefcase')['default']
    IMdiCalendar: typeof import('~icons/mdi/calendar')['default']
    IMdiClock: typeof import('~icons/mdi/clock')['default']
    IMdiDownload: typeof import('~icons/mdi/download')['default']
    IMdiEye: typeof import('~icons/mdi/eye')['default']
    IMdiGithub: typeof import('~icons/mdi/github')['default']
    IMdiLinkedin: typeof import('~icons/mdi/linkedin')['default']
    IMdiSourceBranch: typeof import('~icons/mdi/source-branch')['default']
    IMdiTwitter: typeof import('~icons/mdi/twitter')['default']
    IMdiYoutube: typeof import('~icons/mdi/youtube')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
